spring:
  datasource:
    url: jdbc:postgresql://192.168.246.64:6432/test?autoReconnect=true
    username: ccs
    password: ccs
#    url: jdbc:postgresql://localhost:5432/localdb
#    username: postgres
#    password: ss1108lx


  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    hibernate.ddl-auto: none
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.show_sql: false
      hibernate.use_sql_comments: false
      hibernate.format_sql: false
      javax.persistence.sharedCache.mode: NONE

  flyway.enabled: true
  flyway:
    url: jdbc:postgresql://192.168.246.64:6432/test?autoReconnect=true
    locations: classpath:migration
    schemas: public
    user: ccs
    password: ccs
    baselineOnMigrate: true

  kafka:
    bootstrap-servers: localhost:9092 # 29092 для docker-compose
    producer:
      transaction-id-prefix: tx- # включение транзакций Kafka

  docker:
    compose:
      lifecycle-management: none

logging:
  level:
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"

# метрики, prometheus
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

# собственные значения
values:
  nats:
    host: "192.168.246.64:4222"