spring:
  datasource:
    url: jdbc:postgresql://192.168.246.64:6432/test?autoReconnect=true
    username: ccs
    password: ccs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.mypackage: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log
